# Generated by Django 4.1.5 on 2023-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prdanalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_target', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ac_target', models.DecimalField(decimal_places=0, max_digits=10)),
                ('score', models.DecimalField(decimal_places=0, max_digits=4)),
                ('bonus', models.DecimalField(decimal_places=0, max_digits=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
